-- Truncate all tables and restart the IDENTITY sequence
TRUNCATE TABLE quotes RESTART IDENTITY CASCADE;
TRUNCATE TABLE sources RESTART IDENTITY CASCADE;

-- Populate quote table with 4 sources
INSERT INTO sources (name) VALUES ('The Bible');
INSERT INTO sources (name) VALUES ('The Quran');
INSERT INTO sources (name) VALUES ('The Torah');
INSERT INTO sources (name) VALUES ('The Tibetan Book of the Dead');

-- Populate quote table with sample quotes from the 4 sources
INSERT INTO quotes (source_id, text) VALUES (1, 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.');
INSERT INTO quotes (source_id, text) VALUES (1, 'For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God— not by works, so that no one can boast.');
INSERT INTO quotes (source_id, text) VALUES (1, 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And We have certainly created man from clay of altered black mud.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And We have certainly created man in the best of stature.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And We have certainly created man and We know what his soul whispers to him, and We are closer to him than [his] jugular vein.');
INSERT INTO quotes (source_id, text) VALUES (3, 'Hear, O Israel: The LORD our God, the LORD is one.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall love the LORD your God with all your heart and with all your soul and with all your might.');
INSERT INTO quotes (source_id, text) VALUES (3, 'And these words that I command you today shall be on your heart.');
INSERT INTO quotes (source_id, text) VALUES (4, 'The nature of the mind is clear light; it is unproduced and unobstructed.');
INSERT INTO quotes (source_id, text) VALUES (4, 'When a person dies, the mind''s clarity, the luminosity of the mind, dawns.');
INSERT INTO quotes (source_id, text) VALUES (4, 'The essential nature of mind is without birth or cessation; it is empty and without identity.');
INSERT INTO quotes (source_id, text) VALUES (1, 'For God is not a God of confusion but of peace.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Trust in the LORD with all your heart, and do not lean on your own understanding.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.');
INSERT INTO quotes (source_id, text) VALUES (1, 'In all your ways acknowledge him, and he will make straight your paths.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Love is patient and kind; love does not envy or boast; it is not arrogant or rude.');
INSERT INTO quotes (source_id, text) VALUES (2, 'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge.');
INSERT INTO quotes (source_id, text) VALUES (2, 'Allah does not burden a soul beyond that it can bear.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And when My servants ask you concerning Me, indeed I am near. I respond to the invocation of the supplicant when he calls upon Me.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And We have certainly created man in a best form.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And Allah is the best of planners.');
INSERT INTO quotes (source_id, text) VALUES (3, 'Remember the Sabbath day, to keep it holy.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall not murder.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall not steal.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall not take the name of the LORD your God in vain.');
INSERT INTO quotes (source_id, text) VALUES (3, 'Honor your father and your mother.');
INSERT INTO quotes (source_id, text) VALUES (4, 'Let the winds of the heavens now arise; let the winds blow away my sins.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I attain the transcendental wisdom of the Great Perfection, in which all doubts are clarified.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I recognize whatever appears as my projection, and may I understand the nature of the illusion-like phenomena of the six realms.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I remember the instructions of the lama and unite with the primordial wisdom of the path.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I attain the power to dissolve the body of delusion into the expanse of the ground.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Rejoice in the Lord always. I will say it again: Rejoice!');
INSERT INTO quotes (source_id, text) VALUES (1, 'The Lord is my shepherd; I shall not want.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Do not be overcome by evil, but overcome evil with good.');
INSERT INTO quotes (source_id, text) VALUES (1, 'Commit to the LORD whatever you do, and he will establish your plans.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And We have certainly created man from a sperm-drop mixture so that We may test him.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And the sun runs [on course] toward its stopping point. That is the determination of the Exalted in Might, the Knowing.');
INSERT INTO quotes (source_id, text) VALUES (2, 'And whoever is patient and forgives - indeed, that is of the matters [requiring] determination.');
INSERT INTO quotes (source_id, text) VALUES (2, 'Indeed, Allah is with the patient.');
INSERT INTO quotes (source_id, text) VALUES (2, 'So whoever does an atom''s weight of good will see it.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall not commit adultery.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall not covet your neighbor''s house; you shall not covet your neighbor''s wife, or his male servant, or his female servant, or his ox, or his donkey, or anything that is your neighbor''s.');
INSERT INTO quotes (source_id, text) VALUES (3, 'Remember the days of old; consider the years of many generations; ask your father, and he will show you, your elders, and they will tell you.');
INSERT INTO quotes (source_id, text) VALUES (3, 'The LORD bless you and keep you; the LORD make his face to shine upon you and be gracious to you; the LORD lift up his countenance upon you and give you peace.');
INSERT INTO quotes (source_id, text) VALUES (3, 'You shall walk in all the way that the LORD your God has commanded you, that you may live, and that it may go well with you, and that you may live long in the land that you shall possess.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I not wander in the samsara of confused perception.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I recognize all experiences as being the nature of mind.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I not be frightened by the Peaceful and Wrathful Ones.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I recognize my own projections and know them to be my mind.');
INSERT INTO quotes (source_id, text) VALUES (4, 'May I not be confused by the pure realms of the peaceful and wrathful deities.');
